#version 430
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Emitter
{
    uint FlagBits;
    uint Seed;
    uint ParticleHead;
    uint ParticleSize;
    uint TrailHead;
    uint TrailSize;
    uint TrailPhase;
    uint NextEmitCount;
    uint TotalEmitCount;
    uint EmitPointCount;
    float TimeCount;
    float TimeStopped;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
    uint Color;
    mat4x3 Transform;
};

struct Particle
{
    uint FlagBits;
    uint Seed;
    float LifeAge;
    uint InheritColor;
    uvec2 Velocity;
    uint Color;
    uint Padding;
    mat4x3 Transform;
};

struct Constants
{
    vec3 CameraPos;
    float DeltaTime;
    vec3 CameraFront;
    float Reserved;
    mat4 ProjMat;
    mat4 CameraMat;
    mat4x3 BillboardMat;
    mat4x3 YAxisBillboardMat;
};

struct ParameterSet
{
    int EmitCount;
    int EmitPerFrame;
    float EmitOffset;
    uint Padding0;
    vec2 LifeTime;
    uint EmitShapeType;
    uint Padding1;
    vec4 EmitShapeData[2];
    vec3 Direction;
    float Spread;
    vec2 InitialSpeed;
    vec2 Damping;
    vec4 InitialAngleScale[2];
    vec4 TargetAngleScale[2];
    vec3 Gravity;
    uint Padding2;
    vec3 VortexCenter;
    float VortexRotation;
    vec3 VortexAxis;
    float VortexAttraction;
    float TurbulencePower;
    uint TurbulenceSeed;
    float TurbulenceScale;
    float TurbulenceOctave;
    uint RenderState;
    uint ShapeType;
    uint ShapeData;
    float ShapeSize;
    float Emissive;
    float FadeIn;
    float FadeOut;
    uint ColorFlags;
    uvec2 ColorStart;
    uvec2 ColorEnd;
    uint ColorTexIndex;
    uint NormalTexIndex;
    uint TexState;
    uint Padding3;
};

layout(set = 0, binding = 2, std140) uniform cb2
{
    layout(row_major) Emitter emitter;
} _88;

layout(set = 2, binding = 0, std430) buffer Particles
{
    layout(row_major) Particle _data[];
} Particles_1;

layout(set = 0, binding = 0, std140) uniform cb0
{
    layout(row_major) Constants constants;
} _160;

layout(set = 0, binding = 1, std140) uniform cb1
{
    ParameterSet paramSet;
} _167;

uvec2 PackFloat4(vec4 v)
{
    uvec4 v16 = uvec4(packHalf2x16(vec2(v.x, 0.0)), packHalf2x16(vec2(v.y, 0.0)), packHalf2x16(vec2(v.z, 0.0)), packHalf2x16(vec2(v.w, 0.0)));
    return uvec2(v16.x | (v16.y << uint(16)), v16.z | (v16.w << uint(16)));
}

uvec2 PackFloat4(vec3 v3, float v1)
{
    vec4 param = vec4(v3, v1);
    return PackFloat4(param);
}

void _main(uvec3 dtid)
{
    uint particleID = _88.emitter.ParticleHead + dtid.x;
    Particle particle;
    particle.FlagBits = 0u;
    particle.Seed = 0u;
    particle.LifeAge = 0.0;
    particle.InheritColor = 0u;
    particle.Color = 0u;
    particle.Padding = 0u;
    vec3 param = vec3(0.0);
    float param_1 = 0.0;
    particle.Velocity = PackFloat4(param, param_1);
    particle.Transform = mat4x3(vec3(0.0), vec3(0.0), vec3(0.0), vec3(0.0));
    Particles_1._data[particleID].FlagBits = particle.FlagBits;
    Particles_1._data[particleID].Seed = particle.Seed;
    Particles_1._data[particleID].LifeAge = particle.LifeAge;
    Particles_1._data[particleID].InheritColor = particle.InheritColor;
    Particles_1._data[particleID].Velocity = particle.Velocity;
    Particles_1._data[particleID].Color = particle.Color;
    Particles_1._data[particleID].Padding = particle.Padding;
    Particles_1._data[particleID].Transform = particle.Transform;
}

void main()
{
    uvec3 dtid = gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

